platform :ios, '14.0'
inhibit_all_warnings!

def shared_pods
    pod 'Alamofire', '~> 5.2'
    pod 'AlamofireImage', '~> 4.1'
end

target 'Trouver' do
    shared_pods
end

target 'TrouverTests' do
    shared_pods
end

target 'TrouverUITests' do
    shared_pods
end