excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - implicit_getter
  - trailing_whitespace
