# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Trouver' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Trouver
  pod 'GoogleSignIn'
  pod 'GooglePlaces'
  pod 'SwiftJWT'

  target 'TrouverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrouverUITests' do
    # Pods for testing
  end

end
